revision: 20250119
versions:
  v0.5.2:
    - latest
    - v0.5
    - v0.5.2
  v0.5.1:
    - v0.5.1
  v0.5.0:
    - v0.5.0
registries:
  git.b0t.at:
    user_variable: GIT_B0T_AT_USERNAME
    password_variable: GIT_B0T_AT_PASSWORD
    organisation_variable: GIT_B0T_AT_ORGANISATION
