revision: 20250119
versions:
  v0.5.2:
    - latest
    - v0.5
    - v0.5.2
  v0.5.1:
    - v0.5.1
  v0.5.0:
    - v0.5.0
registries:
  docker.io:
    user_variable: DOCKER_USERNAME
    password_variable: DOCKER_PASSWORD
  quay.io:
    user_variable: QUAY_USERNAME
    password_variable: QUAY_PASSWORD
