revision: 20250119
versions:
  v0.5.4-alpha:
    - latest
    - v0.5
    - v0.5.4-alpha
registries:
  git.b0t.at:
    user_variable: GIT_B0T_AT_USERNAME
    password_variable: GIT_B0T_AT_PASSWORD
    organisation_variable: GIT_B0T_AT_ORGANISATION
