name: Build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          install: true
      - name: Get Docker versions
        run: |
          docker -v
          docker compose version
      - name: Build
        run: go run build.go
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GIT_B0T_AT_ORGANISATION: ${{secrets.GIT_B0T_AT_ORGANISATION}}
